services:
  postgres:
    image: postgres:15
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: VehiculosDB
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: xasmdno123XAW2342as
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: