services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-audit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    networks:
      - audit-net
  audit-database:
    image: postgres:16-alpine
    container_name: audit-database
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: audit_user
      POSTGRES_PASSWORD: xasmdno123XAW2342asasd
    ports:
      - "5450:5432"
    volumes:
      - audit_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U audit_user -d audit_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  audit_postgres_data:

networks:
  audit-net:
    driver: bridge
