apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: usuarios-db
  namespace: app-parqueadero
spec:
  serviceName: usuarios-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: usuarios-db
  template:
    metadata:
      labels:
        app: usuarios-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "UsuariosDB"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: usuarios-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: usuarios-password
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "admin_user", "-d", "UsuariosDB"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: usuarios-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: usuarios-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-db
  namespace: app-parqueadero
spec:
  selector:
    app: usuarios-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-db-headless
  namespace: app-parqueadero
spec:
  clusterIP: None
  selector:
    app: usuarios-db
  ports:
    - port: 5432
      targetPort: 5432
