apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: app-parqueadero
type: Opaque
data:
  usuarios-user: YWRtaW5fdXNlcg==
  usuarios-password: eGFzbWRubzEyM1hBVzIzNDJhcw==
  vehiculos-user: YWRtaW5fdXNlcg==
  vehiculos-password: eGFzbWRub2FzZDY1MTY4emNz
  tickets-user: YWRtaW5fdXNlcg==
  tickets-password: dDFjazN0c1A0c3NYMjM0MmFz
  trazabilidad-user: YWRtaW5fdXNlcg==
  trazabilidad-password: eGFzbWRubzEyM1hBVzIzNDJhcw==
  audit-user: YXVkaXRfdXNlcg==
  audit-password: eGFzbWRubzEyM1hBVzIzNDJhc2FzZA==
  zonas-user: YWRtaW5fdXNlcg==
  zonas-password: eGFzNTJzZjZ6eGMxMjNYQVcyNWFzZHp4a21hcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: app-parqueadero
type: Opaque
data:
  JWT_SECRET: c3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: app-parqueadero
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-db-credentials
  namespace: app-parqueadero
type: Opaque
data:
  POSTGRES_DB: a29uZw==
  POSTGRES_USER: a29uZw==
  POSTGRES_PASSWORD: a29uZ3Bhc3M=
