apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: app-parqueadero
data:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: app-parqueadero
data:
  KONG_DATABASE: "postgres"
  KONG_PG_HOST: "kong-db"
  KONG_PG_USER: "kong"
  KONG_PG_DATABASE: "kong"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-config
  namespace: app-parqueadero
data:
  URLS_PRIMARY_NAME: "Usuarios"
  URLS: '[{"name":"Vehiculos","url":"http://kong-proxy:8000/vehiculos/api-json"},{"name":"Usuarios","url":"http://kong-proxy:8000/usuarios/docs-json"},{"name":"Zonas","url":"http://kong-proxy:8000/zonas/v3/api-docs"},{"name":"Trazabilidad","url":"http://kong-proxy:8000/trazabilidad/docs-json"},{"name":"Tickets","url":"http://kong-proxy:8000/tickets/docs-json"}]'
